[template]
keys = [
"{{project_slug}}/{{env}}/upstream",
]
owner = "nginx"
mode = "0644"
src = "nginx-{{project_slug}}-{{env}}.tmpl"
dest = "/etc/nginx/sites-enabled/{{project_slug}}-{{env}}.conf"
check_cmd = "/usr/sbin/nginx -t -c /etc/nginx/nginx.conf"
reload_cmd = "/usr/sbin/service nginx reload"
