---
- name: install certificate
  copy: src=prod.ssl.crt dest=/etc/ssl/certs/prod.ssl.crt

- name: install private key
  copy:
    content="{{ prod_ssl_key }}"
    dest="/etc/ssl/private/prod.ssl.key"
    owner=root
    group=root
    mode=0600

- name: ensure nginx server is started
  service: name=nginx state=restarted enabled=yes
  sudo: true